import type { StaffRole } from '@dental-ms/shared-types';

/** Permission labels for the matrix table */
export const PERMISSION_LABELS: Record<string, string> = {
  viewPatients: 'View patients',
  editPatients: 'Edit patients',
  viewAppointments: 'View appointments',
  editAppointments: 'Edit appointments',
  viewTreatments: 'View treatments',
  editTreatments: 'Edit treatments',
  viewBilling: 'View billing',
  editBilling: 'Edit billing',
  viewInventory: 'View inventory',
  editInventory: 'Edit inventory',
  viewStaff: 'View staff',
  editStaff: 'Edit staff',
  viewReports: 'View reports',
  manageBranch: 'Manage branch',
  manageAllBranches: 'Manage all branches',
};

/** Role -> permissions (static matrix) */
export const ROLE_PERMISSIONS: Record<StaffRole, Record<string, boolean>> = {
  SuperAdmin: {
    viewPatients: true,
    editPatients: true,
    viewAppointments: true,
    editAppointments: true,
    viewTreatments: true,
    editTreatments: true,
    viewBilling: true,
    editBilling: true,
    viewInventory: true,
    editInventory: true,
    viewStaff: true,
    editStaff: true,
    viewReports: true,
    manageBranch: true,
    manageAllBranches: true,
  },
  BranchAdmin: {
    viewPatients: true,
    editPatients: true,
    viewAppointments: true,
    editAppointments: true,
    viewTreatments: true,
    editTreatments: true,
    viewBilling: true,
    editBilling: true,
    viewInventory: true,
    editInventory: true,
    viewStaff: true,
    editStaff: true,
    viewReports: true,
    manageBranch: true,
    manageAllBranches: false,
  },
  Doctor: {
    viewPatients: true,
    editPatients: true,
    viewAppointments: true,
    editAppointments: true,
    viewTreatments: true,
    editTreatments: true,
    viewBilling: false,
    editBilling: false,
    viewInventory: false,
    editInventory: false,
    viewStaff: false,
    editStaff: false,
    viewReports: true,
    manageBranch: false,
    manageAllBranches: false,
  },
  Receptionist: {
    viewPatients: true,
    editPatients: true,
    viewAppointments: true,
    editAppointments: true,
    viewTreatments: false,
    editTreatments: false,
    viewBilling: true,
    editBilling: true,
    viewInventory: false,
    editInventory: false,
    viewStaff: false,
    editStaff: false,
    viewReports: false,
    manageBranch: false,
    manageAllBranches: false,
  },
  Nurse: {
    viewPatients: true,
    editPatients: true,
    viewAppointments: true,
    editAppointments: true,
    viewTreatments: true,
    editTreatments: true,
    viewBilling: false,
    editBilling: false,
    viewInventory: false,
    editInventory: false,
    viewStaff: false,
    editStaff: false,
    viewReports: false,
    manageBranch: false,
    manageAllBranches: false,
  },
};

export const ROLE_LABELS: Record<StaffRole, string> = {
  SuperAdmin: 'Super Admin',
  BranchAdmin: 'Branch Admin',
  Doctor: 'Doctor',
  Receptionist: 'Receptionist',
  Nurse: 'Nurse',
};

export const DAYS_OF_WEEK = [
  { value: 0, label: 'Sunday' },
  { value: 1, label: 'Monday' },
  { value: 2, label: 'Tuesday' },
  { value: 3, label: 'Wednesday' },
  { value: 4, label: 'Thursday' },
  { value: 5, label: 'Friday' },
  { value: 6, label: 'Saturday' },
];
